sourceDataDir: './fixtures' # relative to project root
cache:
  enabled: true
  loadTimeout: 25000 # maximum time to load data from cache, in milliseconds
redisConnection:
  host: 127.0.0.1
  port: 6379
  cacheTtl: 604800 # cache time to live, a week by default
